### PR TITLE
Added initial implementation of the Property API, as per Issue #1.

### PR DESCRIPTION
**Pull request by mikebaum**
Created a pull request to merge my initial implementation of the Property API. I will merge this into master in a week or so.

This pull request was created for the sole purpose of providing a way to review the api. This PR pertains to Issue #1.

### CODE REVIEW

**Comment by mikebaum** [comment]
@dacianpitic @petikoch

Here's the first commit on the Property API. I pinged you in case you're interesting in reviewing it. It's a lot of code so I'm not expecting you to review it all, but you can if you want.

Suggestions and feedback are welcomed.

Cheers,

Mike

**Comment by Petikoch** [comment]
Hi @mikebaum,

thanks for the invitation to have a look at your project. I didn't read everything, just scanned some parts of it...

Some random thoughts from me...
- In the SynchronizedTextFieldApp example, I can see a "View-Class" and a "Model-Class". There is no such thing as a "ViewModel-Class". The project is implementing the MVVM architecture, right? 
- The PropertyImpl insists of being accessed by something like "the GUI-Thread". What about a thread-safe Property implementation instead? Would be easier to use by background threads. In practice only the View objects must be accessed by the "right thread". In know, also the JavaFx-Properties enforce the threading like you do it here... but why not think about a thread-safe viewmodel? And a thread-switch in the binding to the view? What about enforcing the right thread for the Swing GUI in a custom EventQueue (Swing View) implementation? 
- At the moment, the project depends on RxJava. But only a little bit. It has it's own Observer, Source, Observable ... I'd go either fully RxJava (with RxSwing, RxJavaFX, ...) and benefit from it's API power, or drop it.

Have a nice day!

Best regards,
Peti

**Comment by mikebaum** [comment]
@Petikoch 
Thanks for the feedback...
Before I address you're questions, I just wanted to check if you read the [README](https://github.com/mikebaum/RxUI/blob/master/README.md) for the project. If not, take a moment to read that, it might help to explain my motivation and the _raison-d’être_ for this library.
1. Regarding the Test app -  The purpose was mostly to demonstrate how properties work. As far as model, view and viewmodel classes, I have an idea in my head, but I didn't want to work on that till I got the property api right. Your observation is correct, in my test app, I should have named the TextModel -> TextViewModel instead. I have held back from writing those abstractions since I was hoping to have a discussion first. What you've created already in your project is a good idea and I think it would benefit from the binding api, a property provides. 
2. PropertyImpl - Good observation about that class. It might be interesting to have 3 property classes, specifically:
   1. **ViewProperty**
      - Strict Thread enforcement
      - only used to front the underlying ui component
      - must prevent re-entrancy
   2. **ViewModelProperty**
      - Thread safe (as you suggest) - can receive updates on any thread and guarantees to update the ViewProperty only on the appropriate thread.
      - Would need to be able to handle errors and forward them to the ui for the purpose of alerting the user in some way.
      - This property could expose a broader api and be more pure Rx
      - It should still prevent re-entrancy, because a binding loop in the ViewModel layer would be just as catastrophic as in the View layer.
   3. **ModelProperty**
      - Background Thread only
      - Attempts to set/get values from a UI thread should blow up in exactly the inverse way as the ViewProperty. Specifically, any attempts to interact with a ModelProperty from a UI thread should be persona non grata.
      - re-entrancy here should also probably be forbidden
      - must forward errors to the ViewModelProperty
      - could be almost pure Rx
   
   Each of these properties would need their own implementation of bind and synchronize which would take care of the threading contracts. Better yet maybe this binding aspect could be abstracted in PropertyBinder object. This would be not too far from what you've done with your `Bindable` class.
   
   It may seems like a small thing to provide a specialized api for properties rather than just using Rx, but from my perspective, it makes it easier for the beginner/novice to get into Rx. I know from experience that it takes time to learn Rx and not everyone gets it. The Property api could therefore be considered Rx light. However, offering an easy way to turn a property into a Rx Observable would allow the more expert user to take advantage of the advanced features. I see the property object on par with Single, in the sense that they identified a use case that was being covered already but could be better/cleaner/clearer.
3. Regarding Rx in the Property API
   You're correct to observe that it seems I'm on the fence about whether or not to include Rx in the property. This really represents the fact that I'm not sure yet. In fact as I started to implement Issue #2 (will be committed soon), I have realized that I need to follow the model that Rx puts for, i.e. Property and PropertyObservable should be classes and they should require that you pass an object like OnSubsubscribe when constructing. The key difference is that all Properties are hot observables and should always be live, therefore I don't want them to be lazy. Streams of events should of course be lazy but not Properties. Keep in mind a property is a replacement for a mutable field, therefore it should always have a value. It should give you everything you get from a plain old field with the addition of a reactive api.

So, sorry about the long post, I just felt like doing a brain dump. I don't do that enough. Anyway, I have a proposal, why not create a project that both you and I own that we could work together on this. If you're not interested that's okay, I'll keep on plugging along, but it seems like it would be interesting to collaborate. In fact the other day I created an GitHub Organization called [ReactiveUI-JVM](https://github.com/ReactiveUI-JVM).

**Comment by mikebaum** [comment]
Having slept on it one night I have reversed my thinking again. Here's how I see things, this morning... :)
1. **View** - Abstraction for the actual component that is on the screen. It should expose a method to get the actual component (as a JComponent) and a set of Properties that can be used for binding.
2. **ViewModel** - Some model that is directly bound to a View. It should contain all the logic and data that is to be presented in the View in the form of Properties. It should know how to transform Model data into something presentable to a View.
3. **Model** - An abstraction that is used to cache the actual data as is (or will be) persisted somewhere. A ViewModel would bind itself to a Model.

Fundamentally, these three layers have distinct responsibilities and it really has nothing to do with threading at all. Threading only comes into the picture, since persisting/fetching data is long running and we don't want to block the event loop. With that in mind, then the only thing that needs to be thread savvy is the object that actually performs the IO (or other long running task). This could be an `Observable`, using `subscribeOn(background thread).observeOn(event thread)` or an actor that receives request and sends responses (on the event loop) or anything else you could imagine. So therefore in my opinion all three of the mentioned layers could and should be interacted with only on the event loop. Having that in mind, then there doesn't really seem to be a need for more than one type of Property. The only reason I could think to have more than one Property type would be if a property in one layer would need to have methods that aren't necessary in another. This could very well be the case.

**Comment by mikebaum** [comment]
I'm closing this PR since a better version of the initial property api has been implemented in PR #4 as part of Issue #3.

**Comment by Petikoch** [comment]
Hi @mikebaum ,

at the moment I have not the time to build something like a "Reactive Java MVVM GUI" library. Although I'd like to "have one" :-). I think it's a large task to build such a library. Probably takes around a few months, if it is something serious including advanced features like undo/redo, validation, view-technology agnosticity... 

I'm sure, there is a market for such a library. There are a lot of Swing GUI's out there, a lot of JavaFX GUI's, and e.g. a lot of Vaadin-GUI's which would also fit nicely to this library.

There are other solutions already out there like mmvFX, DataFX, the Dolphin-Platform or RxSwing+RxJava, covering more or less aspects like 
- local or distributed solution
- Swing GUI?
- JavaFX GUI?
- Just JVM?
- Also Web?

For me, the RxSwing+RxJava based approach works fine. I don't see the issues you describe concerning e.g. BehaviourSubject.

Best regards,
Peti

**Comment by Petikoch** [comment]
Regarding the three types of explicit Properties... ViewProperty, ViewModelProperty, ModelProperty. 

I only see the need to create something like a ViewModelProperty. Why? Because a view has already it's properties. E.g. a JLabel has it's text property. Just bind the original JLabel text property to the ViewModelProperty. Why introduce another indirection/abstraction? The viewmodel IS this indirection/abstraction. Same on the model side. The model is just a (potential) stateless facade to the business logic. We just need to interact with this facade. 

Am I missing something?

Best regards,
Peti

**Comment by mikebaum** [comment]
@Petikoch 
Yes, I agree there only needs to be one Property and it should just be called Property. I have already added a means to create Properties from Swing components. Right now, there is only one example so far, see `TextPropertySource`. The View layer properties help to normalize the View irrespective of toolkit, but are not 100% necessary as you suggest. If the View is normalized in this manner you might be able to reuse even more code if you want to swap Swing for JavaFx for example. In that case you'd just need to change the View to be based on a JavaFx component, but otherwise interacting with it would be the same. Further having a means to transform a JComponent of some kind into a String, Integer, Boolean, or ??? Property seems infinitely useful, since it removes noise from your code.

Cheers,
Mike

**Comment by Petikoch** [comment]
@mikebaum, sounds good.

I encourage you to create the necessary features together with appropriate examples to get a feel if everything "feels right". 

Best regards from Switzerland!
Peti

**Pull request closed without merging**
